language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux
  - osx

notifications:
  email:
    - sunbergzach@gmail.com

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia --project -e 'import Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include("docs/make.jl")'
